name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Установка зависимостей
        run: |
          cd functions
          npm install

      - name: Деплой Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
